// default package
// Generated 2016-5-31 9:22:33 by Hibernate Tools 4.3.1.Final



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String uuid;
     private String name;

    public Users() {
    }

	
    public Users(String uuid) {
        this.uuid = uuid;
    }
    public Users(String uuid, String name) {
       this.uuid = uuid;
       this.name = name;
    }
   
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


